name: Trigger Flathub Update

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specific tag to update to (optional)'
        required: false
        type: string
      force:
        description: 'Force update even if tag is the same'
        required: false
        type: boolean
        default: false

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger update workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: new-release
          client-payload: '{"tag": "${{ github.event.inputs.tag }}", "force": "${{ github.event.inputs.force }}"}' 